before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./
    binary: pira
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  prerelease: auto
brews:
  - name: pira
    homepage: https://github.com/piaverous/pira
    description: Generate Terraform moved blocks automatically for painless refactoring
    license: Apache-2.0
    tap:
      owner: piaverous
      name: tap
    install: |
      bin.install "pira"
    test: |
      system "#{bin}/pira -version"
